### ISSUE TITLE
Example form not working

### ISSUE THREAD

**Issue by benoj** [zabute/formsy-semantic-ui-react#33]
Hi, 

I've copied the example from the readme, however, the form is still submitting and no validations seem to be working?

Here are my versions: "semantic-ui-react": "^0.77.2","formsy-react": "^1.1.4", "formsy-semantic-ui-react": "^0.3.2",

**Comment by zabute** [comment]
Hi
The form on the readme wont't show any errors if you simply submit it because it doesn't have any required fields. Did you try and input an invalid email?

Also, You should go to the [example](https://github.com/zabute/formsy-semantic-ui-react/tree/master/example) folder and look at the examples there.
