### ISSUE TITLE
Only import needed components from sematic ui react instead of the whole package

### ISSUE THREAD

**Issue by namnm** [zabute/formsy-semantic-ui-react#49]
We should only import the components we need, or use a babel plugin to transform the code: https://www.npmjs.com/package/babel-plugin-transform-semantic-ui-react-imports

**Comment by ksaitor** [comment]
lol. I've just spent 2 hours debugging, trying to figure out why is my build so bloated…
Thanks to `formsy-semantic-ui-react` it turns out 🙈 
![Screenshot 2019-07-15 at 23 57 46](https://user-images.githubusercontent.com/936436/61230326-67188200-a75c-11e9-946f-97dc7a2a044d.jpg)

**Comment by ksaitor** [comment]
fixed in @ksaitor/formsy-semantic-ui-react
feel free to `yarn add ksaitor/formsy-semantic-ui-react` while it's getted merged

**Comment by namnm** [comment]
@ksaitor Thanks for the fix, I have switched to https://github.com/jaredpalmer/formik to custom my own validations now.. Look like this repo is not active anymore.

**Comment by felixmosh** [comment]
Since v2.0.5 of `formsy-semantic-ui-react` there is tree shaking enabled by default for `semantic-ui` & `formsy-react` & `formsy-semantic-ui-react`.

Before: 
![image](https://user-images.githubusercontent.com/9304194/91529715-7895fc80-e912-11ea-8bed-cc1e9622370e.png)

After:
![image](https://user-images.githubusercontent.com/9304194/91529770-94999e00-e912-11ea-8177-65a8bce6c5e4.png)


Thank you for pointing this out 🙏
