### ISSUE TITLE
Checkbox value does not get sent to server

### ISSUE THREAD

**Issue by colinramsay** [zabute/formsy-semantic-ui-react#90]
When setting a string value on a Checkbox, this value never gets used (i.e. sent to the server). Instead true/false will be used.

## Expected Behavior

Use the value set on the checkbox if it is checked, as with HTML checkboxes.

## Current Behavior
The checked state gets provided as the value.

This definitely seems by design, am I missing something? The `CheckboxRadioValueType` indicates that this _can_ be a string but I don't see the point if it never gets used?

https://github.com/zabute/formsy-semantic-ui-react/blob/master/src/FormsyCheckbox.tsx#L82

**Comment by felixmosh** [comment]
currently Checkbox & Radio are saving boolean values to the model.
The value is the value of `checked`.

I'm not sure what it should be...
Native checkboxes has 2 possible  values, `value` & `checked`... 
I think that it is better to reflect the booleans instead of the value because the `checked` value is what changes when you click on them. 
In this case `value` won't ever change, therefore, it is just like an `data` attribute.

If you need the `value`, you can add `onChange` prop, and it will give you the event & the entire component props (similar to SUIR)

**Comment by colinramsay** [comment]
I think my expectation was that it would behave like the native checkbox input. I’ll take a look at an onChange workaround and report back, thank you.

On Thu, Sep 17, 2020 at 18:33, Felix Mosheev <notifications@github.com> wrote:


currently Checkbox & Radio are saving boolean values to the model.
The value is the value of checked .

I'm not sure what it should be...
Native checkboxes has 2 possible values, value & checked ...
I think that it is better to reflect the booleans instead of the value because the checked value is what changes when you click on them.
In this case value won't ever change, therefore, it is just like an data attribute.

If you need the value , you can add onChange prop, and it will give you the event & the entire component props (similar to SUIR)

**Comment by felixmosh** [comment]
Ping me if you need any other help.

**Comment by colinramsay** [comment]
Using `onChange` with `updateInputsWithValue` works for this, thanks.
